name: Update signals (trend + xsmom)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy xgboost pandas_datareader
      - name: Generate signals and performance
        run: |
          python generate_all.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update all signals and reports
          branch: main
          file_pattern: |
            signals_trend.js
            signals_xsmom.js
            signals.js
            reports/**
            signals.json
